### ISSUE TITLE
Repository Basics

### ISSUE THREAD

**Issue by ElectronicsArchiver** [SoMainline/adt_collection#20]
- Please add a license, for example CC-BY-SA

  https://choosealicense.com/licenses/cc-by-sa-4.0/

  https://choosealicense.com/licenses/

- Disable unused tabs ( `Actions` , `Projects` )

- Disable unused widgets ( `Releaeses` , `Packages` , `Environments` )

- Add a description
  
  ```
  ADT collection from iDevices.
  ```

- Add tags:
  
  - `collection`

  - `list`

  - `adt`

  - `apple`

  - `idevice`

  - `dump`

**Comment by roke-julian-lockhart** [comment]
> https://github.com/SoMainline/adt_collection/issues/20#event-14315734436

@konradybcio, I don't see a `license` file.
