### ISSUE TITLE
iPad Air (MD785LL/A) (software version 12.5.6)

### ISSUE THREAD

**Issue by mightymos** [SoMainline/adt_collection#22]
I have an original iPad Air that I truly do not know what to do with.
Has the device tree ADT thing been dumped for this model?
If not, is someone interested in dumping/hacking on this hardware if mailed?

**Comment by halal-beef** [comment]
I've dumped mine and made a pr https://github.com/SoMainline/adt_collection/pull/24

**Comment by mightymos** [comment]
Thanks mate.
